import Login from '../pages/login'
import Atribuicoes from '../pages/atribuicoes'
import Ativos from '../pages/ativos'


describe('Cadastro de Atribuições', () => {

    beforeEach(() => {
        cy.loginViaApi()
        Login.visitarPagina()
    }) 
    it('Cadastro com Sucesso: Múltiplos Ativos, colaborador e Observações', () => {        
        Atribuicoes.clicarAtribuicoes()
        Atribuicoes.clicarNovaAtribuicao()
        Atribuicoes.selecionarAreaAtribuicao()
        Atribuicoes.selecionarSubareaAtribuicao()
        Atribuicoes.marcarOpcaoColaboradorAtribuicao()
        Atribuicoes.selecionarColaboradorAtribuicao()
        Atribuicoes.selecionarAtendidoPor()
        Atribuicoes.selecionarModalidadePresencialAtribuicao()
        Atribuicoes.selecionarSOAtribuicao()
        Atribuicoes.marcarCheckBoxUtilizaraPacoteOfficeAtribuicao()
        Atribuicoes.selecionarPacoteOfficeAtribuicao()
    })

    it('Cadastro com Sucesso: Único Ativo, Apenas Subárea e Sem Observações', () => {
        Ativos.criarNovoAtivo()
        Atribuicoes.clicarAtribuicoes()
        Atribuicoes.clicarNovaAtribuicao()
        Atribuicoes.selecionarAreaAtribuicao()
        Atribuicoes.selecionarSubareaAtribuicao()
        Atribuicoes.selecionarSubareaSemColaborador()
        Atribuicoes.selecionarColaboradorAtribuicao()
        Atribuicoes.selecionarAtendidoPor()
        Atribuicoes.selecionarModalidadeHomeOfficeAtribuicao()
        Atribuicoes.selecionarSOAtribuicao()
        Atribuicoes.desmarcarCheckBoxUtilizaraPacoteOfficeAtribuicao()
        Atribuicoes.validarCampoDisabledPacoteOfficeAtribuicao()
        Atribuicoes.clicarAtribuirAtivoAtribuicao()
        Atribuicoes.selecionarTomboDoAtivoAtribuicao()
        Atribuicoes.selecionarDescricaoDoAtivoAtribuicao()
        Atribuicoes.selecionarStatusVinculadoDoAtivoAtribuicao()
        Atribuicoes.clicarSalvarAtribuicao()
        Atribuicoes.validarMensagemDeSucessoAtivoVinculado()
    })
    it('Tentativa de Cadastro sem Campos Obrigatórios e sem Ativo Vincular', () => {
        Atribuicoes.clicarAtribuicoes()
        Atribuicoes.clicarNovaAtribuicao()
        Atribuicoes.selecionarSubareaSemColaborador()
        Atribuicoes.selecionarColaboradorAtribuicao()
        Atribuicoes.selecionarSOAtribuicao()
        Atribuicoes.desmarcarCheckBoxUtilizaraPacoteOfficeAtribuicao()
        Atribuicoes.validarCampoDisabledPacoteOfficeAtribuicao()
        Atribuicoes.clicarSalvarAtribuicao()
        Atribuicoes.validarMensagemCampoObrigatorioAreaAtribuicao()
        Atribuicoes.selecionarAreaAtribuicao()
        Atribuicoes.clicarSalvarAtribuicao()
        Atribuicoes.validarMensagemCampoObrigatorioAtendidoPor()
    })
    it('Regra Condicional do Pacote Office', () => {
        Ativos.criarNovoAtivo()
        Atribuicoes.clicarAtribuicoes()
        Atribuicoes.clicarNovaAtribuicao()
        Atribuicoes.selecionarAreaAtribuicao()
        Atribuicoes.selecionarSubareaAtribuicao()
        Atribuicoes.selecionarSubareaSemColaborador()
        Atribuicoes.selecionarColaboradorAtribuicao()
        Atribuicoes.selecionarAtendidoPor()
        Atribuicoes.selecionarModalidadeHomeOfficeAtribuicao()
        Atribuicoes.selecionarSOAtribuicao()
        Atribuicoes.marcarCheckBoxUtilizaraPacoteOfficeAtribuicao()
        Atribuicoes.clicarAtribuirAtivoAtribuicao()
        Atribuicoes.selecionarTomboDoAtivoAtribuicao()
        Atribuicoes.selecionarDescricaoDoAtivoAtribuicao()
        Atribuicoes.selecionarStatusVinculadoDoAtivoAtribuicao()
        Atribuicoes.clicarSalvarAtribuicao()
        Atribuicoes.validarMensagemCampoObrigatorioUtilizaraPacoteOffice()
        
    
    })
    it('Cancelar Operação e Descartar Informações', () => {
        Ativos.criarNovoAtivo()
        Atribuicoes.clicarAtribuicoes()
        Atribuicoes.clicarNovaAtribuicao()
        Atribuicoes.selecionarAreaAtribuicao()
        Atribuicoes.selecionarSubareaAtribuicao()
        Atribuicoes.selecionarSubareaSemColaborador()
        Atribuicoes.selecionarColaboradorAtribuicao()
        Atribuicoes.selecionarAtendidoPor()
        Atribuicoes.selecionarModalidadeHomeOfficeAtribuicao()
        Atribuicoes.selecionarSOAtribuicao()
        Atribuicoes.desmarcarCheckBoxUtilizaraPacoteOfficeAtribuicao()
        Atribuicoes.validarCampoDisabledPacoteOfficeAtribuicao()
        Atribuicoes.clicarAtribuirAtivoAtribuicao()
        Atribuicoes.selecionarTomboDoAtivoAtribuicao()
        Atribuicoes.selecionarDescricaoDoAtivoAtribuicao()
        Atribuicoes.selecionarStatusVinculadoDoAtivoAtribuicao()
        Atribuicoes.clicarBotaoCancelarAtribuicao()
        Ativos.clicarMenuAtivos()
        Ativos.clicarMenuDepositoCTI()
        Ativos.clicarPesquisaESelecionaPorTomboDepositoCTI()
        Ativos.validarTomboPesquisadoNaTabela()
        Ativos.validarStatusDoAtivoNaTabela()

    })
})

