import Login from '../pages/login'
import Atribuicoes from '../pages/atribuicoes'
import Ativos from '../pages/ativos'


describe('Editar Atribuições', () => {

    beforeEach(() => {
        cy.loginViaApi()
        Login.visitarPagina()
    })

    it('Editar Atribuição com Sucesso e Troca de Ativo por Defeito', () => {
        Ativos.criarNovoAtivo()
        Atribuicoes.clicarAtribuicoes()
        Atribuicoes.clicarNovaAtribuicao()
        Atribuicoes.selecionarAreaAtribuicao()
        Atribuicoes.selecionarSubareaAtribuicao()
        Atribuicoes.selecionarSubareaSemColaborador()
        Atribuicoes.selecionarColaboradorAtribuicao()
        Atribuicoes.selecionarAtendidoPor()
        Atribuicoes.selecionarModalidadeHomeOfficeAtribuicao()
        Atribuicoes.selecionarSOAtribuicao()
        Atribuicoes.desmarcarCheckBoxUtilizaraPacoteOfficeAtribuicao()
        Atribuicoes.validarCampoDisabledPacoteOfficeAtribuicao()
        Atribuicoes.clicarAtribuirAtivoAtribuicao()
        Atribuicoes.selecionarTomboDoAtivoAtribuicao()
        Atribuicoes.selecionarDescricaoDoAtivoAtribuicao()
        Atribuicoes.selecionarStatusVinculadoDoAtivoAtribuicao()
        Atribuicoes.clicarSalvarAtribuicao()
        Atribuicoes.validarMensagemDeSucessoAtivoVinculado()//salva a atribuição com o ativo gerado
        Atribuicoes.clicarEPesquisarTomboCriado()
        Atribuicoes.clicarBtnEditarAtribuicao()
        Atribuicoes.validarTextoAreaAtribuicao()
        Atribuicoes.validarTextoSubareaAtribuicao()
        Atribuicoes.validarTextoAtendidoPorAtribuicao()
    })
    it('Substituição de Ativo Disponível e Inclusão de Novo Equipamento', () => {
        Ativos.criarNovoAtivo()
        Atribuicoes.clicarAtribuicoes()
        Atribuicoes.clicarNovaAtribuicao()
        Atribuicoes.selecionarAreaAtribuicao()
        Atribuicoes.selecionarSubareaAtribuicao()
        Atribuicoes.selecionarSubareaSemColaborador()
        Atribuicoes.selecionarColaboradorAtribuicao()
        Atribuicoes.selecionarAtendidoPor()
        Atribuicoes.selecionarModalidadeHomeOfficeAtribuicao()
        Atribuicoes.selecionarSOAtribuicao()
        Atribuicoes.desmarcarCheckBoxUtilizaraPacoteOfficeAtribuicao()
        Atribuicoes.validarCampoDisabledPacoteOfficeAtribuicao()
        Atribuicoes.clicarAtribuirAtivoAtribuicao()
        Atribuicoes.selecionarTomboDoAtivoAtribuicao()
        Atribuicoes.selecionarDescricaoDoAtivoAtribuicao()
        Atribuicoes.selecionarStatusVinculadoDoAtivoAtribuicao()
        Atribuicoes.clicarSalvarAtribuicao()
        Atribuicoes.validarMensagemDeSucessoAtivoVinculado()
        Ativos.criarNovoAtivo('tomboCriado2')//cria um novo ativo para substituir o ativo vinculado na atribuição
        Atribuicoes.clicarAtribuicoes()
        Atribuicoes.clicarEPesquisarTomboCriado('tomboCriado')
        Atribuicoes.clicarBtnEditarAtribuicao()
        Atribuicoes.alterarStatusDoTombo('tomboCriado', '1')//altera o status do ativo criado para Disponível
        Atribuicoes.selecionarAtendidoPor()
        Atribuicoes.removerTombo('tomboCriado')
        Atribuicoes.abrirEPesquisarTomboParaEditar('tomboCriado2') //inclui o ativo na atribuição
        Atribuicoes.clicarSalvarAtribuicao()
        Atribuicoes.clicarEPesquisarTomboCriado('tomboCriado2')
        Atribuicoes.clicarBtnVisualizarAtivos()
        Atribuicoes.validarDadosDoTomboNoModal('tomboCriado2', 'CAMERA Teste Teste', 'DISPONÍVEL')//valida se o ativo vinculado na atribuição é o ativo criado para substituir o ativo anterior
    })

    it('Tentativa de Remoção por Defeito sem Informar o Motivo', () => {
        Ativos.criarNovoAtivo()
        Atribuicoes.clicarAtribuicoes()
        Atribuicoes.clicarNovaAtribuicao()
        Atribuicoes.selecionarAreaAtribuicao()
        Atribuicoes.selecionarSubareaAtribuicao()
        Atribuicoes.selecionarSubareaSemColaborador()
        Atribuicoes.selecionarColaboradorAtribuicao()
        Atribuicoes.selecionarAtendidoPor()
        Atribuicoes.selecionarModalidadeHomeOfficeAtribuicao()
        Atribuicoes.selecionarSOAtribuicao()
        Atribuicoes.desmarcarCheckBoxUtilizaraPacoteOfficeAtribuicao()
        Atribuicoes.validarCampoDisabledPacoteOfficeAtribuicao()
        Atribuicoes.clicarAtribuirAtivoAtribuicao()
        Atribuicoes.selecionarTomboDoAtivoAtribuicao()
        Atribuicoes.selecionarDescricaoDoAtivoAtribuicao()
        Atribuicoes.selecionarStatusVinculadoDoAtivoAtribuicao()
        Atribuicoes.clicarSalvarAtribuicao()
        Atribuicoes.validarMensagemDeSucessoAtivoVinculado()
        Ativos.criarNovoAtivo('tomboCriado2')//cria um novo ativo para substituir o ativo vinculado na atribuição
        Atribuicoes.clicarAtribuicoes()
        Atribuicoes.clicarEPesquisarTomboCriado('tomboCriado')
        Atribuicoes.clicarBtnEditarAtribuicao()
        Atribuicoes.alterarStatusDoTombo('tomboCriado', '2')//altera o status do ativo criado para Disponível
        Atribuicoes.selecionarAtendidoPor()
        Atribuicoes.removerTombo('tomboCriado')
        Atribuicoes.clicarSalvarAtribuicao()
        Atribuicoes.validarMensagemObrigatorioAtivoComDefeito()
    })

    it('Validação de Campos Obrigatórios e Lista de Ativos Vazios na Edição', () => {
        Ativos.criarNovoAtivo()
        Atribuicoes.clicarAtribuicoes()
        Atribuicoes.clicarNovaAtribuicao()
        Atribuicoes.selecionarAreaAtribuicao()
        Atribuicoes.selecionarSubareaAtribuicao()
        Atribuicoes.selecionarSubareaSemColaborador()
        Atribuicoes.selecionarColaboradorAtribuicao()
        Atribuicoes.selecionarAtendidoPor()
        Atribuicoes.selecionarModalidadeHomeOfficeAtribuicao()
        Atribuicoes.selecionarSOAtribuicao()
        Atribuicoes.desmarcarCheckBoxUtilizaraPacoteOfficeAtribuicao()
        Atribuicoes.validarCampoDisabledPacoteOfficeAtribuicao()
        Atribuicoes.clicarAtribuirAtivoAtribuicao()
        Atribuicoes.selecionarTomboDoAtivoAtribuicao()
        Atribuicoes.selecionarDescricaoDoAtivoAtribuicao()
        Atribuicoes.selecionarStatusVinculadoDoAtivoAtribuicao()
        Atribuicoes.clicarSalvarAtribuicao()
        Atribuicoes.validarMensagemDeSucessoAtivoVinculado()//salva a atribuição com o ativo gerado
        Atribuicoes.clicarEPesquisarTomboCriado()
        Atribuicoes.clicarBtnEditarAtribuicao()
        Atribuicoes.apagarAreaDaAtribuicaoDoAtivo()
        Atribuicoes.clicarSalvarAtribuicao()
        Atribuicoes.validarTextoAreaAtribuicao('Selecione ...')
        Atribuicoes.selecionarAreaAtribuicao()
        Atribuicoes.selecionarSubareaAtribuicao()
        Atribuicoes.removerTombo('tomboCriado')
        Atribuicoes.selecionarAtendidoPor()
        Atribuicoes.clicarSalvarAtribuicao()
        Atribuicoes.validarMensagemDeAlertaAtivoNaoInformado()
    })

    it('Cancelar Edição da Atribuição', () => {
        Ativos.criarNovoAtivo()
        Atribuicoes.clicarAtribuicoes()
        Atribuicoes.clicarNovaAtribuicao()
        Atribuicoes.selecionarAreaAtribuicao()
        Atribuicoes.selecionarSubareaAtribuicao()
        Atribuicoes.selecionarSubareaSemColaborador()
        Atribuicoes.selecionarColaboradorAtribuicao()
        Atribuicoes.selecionarAtendidoPor()
        Atribuicoes.selecionarModalidadeHomeOfficeAtribuicao()
        Atribuicoes.selecionarSOAtribuicao()
        Atribuicoes.desmarcarCheckBoxUtilizaraPacoteOfficeAtribuicao()
        Atribuicoes.validarCampoDisabledPacoteOfficeAtribuicao()
        Atribuicoes.clicarAtribuirAtivoAtribuicao()
        Atribuicoes.selecionarTomboDoAtivoAtribuicao()
        Atribuicoes.selecionarDescricaoDoAtivoAtribuicao()
        Atribuicoes.selecionarStatusVinculadoDoAtivoAtribuicao()
        Atribuicoes.clicarSalvarAtribuicao()
        Atribuicoes.validarMensagemDeSucessoAtivoVinculado()//salva a atribuição com o ativo gerado
        Atribuicoes.clicarEPesquisarTomboCriado()
        Atribuicoes.clicarBtnEditarAtribuicao()
        Atribuicoes.selecionarAreaAtribuicao('ADNIS')
        Atribuicoes.selecionarModalidadePresencialAtribuicao()
        Atribuicoes.removerTombo('tomboCriado')
        Atribuicoes.clicarBotaoCancelarAtribuicao()
        Atribuicoes.clicarEPesquisarTomboCriado()
        Atribuicoes.clicarBtnEditarAtribuicao()
        Atribuicoes.validarTextoAreaAtribuicao('CONSULTORIA')
        Atribuicoes.validarModalidadeAtribuicao('Home Office')
        Atribuicoes.clicarBotaoCancelarAtribuicao()
        Atribuicoes.clicarEPesquisarTomboCriado()
        Atribuicoes.clicarBtnVisualizarAtivos()
        Atribuicoes.validarDadosDoTomboNoModal('tomboCriado', 'CAMERA Teste Teste', 'VÍNCULADO')
    })
})